name: fitness_app
description: Comp 380 Semester Project. Tony Nguyen. David Quines. Jane Cabanayan. Ben La France

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_splash: ^1.0.0
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  path: ^1.6.4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #sqflite:
  #path:


flutter:

  uses-material-design: true

  assets:
    - assets/gifs/splashScreen.gif
    - assets/exerciseList.json
    - assets/databases/exercises.db
